### ISSUE TITLE
Tree widget: the eye icon is misaligned when density is "enlarged"

### ISSUE THREAD

**Issue by JoanaSmit** [iTwin/viewer-components-react#1015] opened 2024-08-13 09:08 UTC
@itwin/tree-widget-react **1.x** (expected alignment):
![image](https://github.com/user-attachments/assets/89f32608-be0a-48b2-91a9-d5e7fdac51b7)

@itwin/tree-widget-react **2.x**:
![image](https://github.com/user-attachments/assets/368bd791-a4f5-4b2c-95ec-a34315312a3a)

**Comment by MartynasStrazdas** [comment] 2024-09-20 08:06
@JoanaSmit I was unable to reproduce this, could you provide more information like the exact `tree-widget` and `itwinUI` versions. Perhaps you have any custom css. Do you still have this issue with `tree-widget` 2.x.

**Comment by JoanaSmit** [comment] 2024-09-27 09:14
@MartynasStrazdas sorry for the delayed reply.
We're using `@itwin/tree-widget-react 2.3.3` and `@itwin/itwinui-react 3.13.4` (I also tried updating `itwinui-react` to 3.15.1). 
The web inspector shows that `margin-left` comes from _.../node_modules/@itwin/tree-widget-react/lib/esm/components/trees/common/TreeRenderer.scss_
![image](https://github.com/user-attachments/assets/14ea80d5-2393-49eb-b0e7-42fd0d48ea28)
![image](https://github.com/user-attachments/assets/d2bf5e42-9318-4589-8767-2c85a4db4792)

**Comment by saskliutas** [comment] 2024-10-01 15:48
Should be fixed in `@itwin/tree-widget-react@2.3.4`

**Closed by saskliutas** 2024-10-01 15:48 UTC
Labels: bug, tree widget
