### ISSUE TITLE
Property grid no longer refreshes correctly after changing a value

### ISSUE THREAD

**Issue by Rock2000** [iTwin/viewer-components-react#721] opened 2023-12-29 22:01 UTC
We use "@itwin/property-grid-react": "^1.4.0" in our Studio app. It has been working fine, and works OK in a previous Studio that relied on itwin core 4.3.0-dev.25. When we update to a newer Studio host, which brings itwin core 4.3.0-dev.37, the property grid does not refresh correctly. When I change, for example, an element's label value, it does get committed to the database, but the propety grid doesn't show the new value. Even if I unselect and reselect the element, which reloads the property grid, the value is still not shown. If I close whole app and reload, then the property grid finally shows the new value.

Since Studio doesn't host this property grid package, the version of this package isn't changing. So it seems like it has to be that this package is having trouble with the newer itwin core (dev.37).

**Comment by grigasp** [comment] 2024-01-02 11:11
I looked at what changed between `dev.25` and `dev.37` and think that this is the cause - https://github.com/iTwin/imodel-native/pull/550. Most likely we're now able to find the cached provider with old data and don't attempt to re-load it. I'll try to reproduce this locally to confirm.

In the meantime, can you try to set the `{ caching: { content: { size: 0 } } }` when initializing `Presentation` on the backend and see if that helps?

**Comment by grigasp** [comment] 2024-01-02 16:26
While it looks like https://github.com/iTwin/imodel-native/pull/550 is what caused this to stop working, I don't think there's anything wrong with the change as it just makes sure we actually use our cache rather than re-create content on each request.

I confirmed we are correctly tracking element changes in the iModel and clearing affected cache entries as necessary. Added a test to prove that it works: [https://github.com/iTwin/itwinjs-core/compare/master...presentation/content-after-imodel-changes](https://github.com/iTwin/itwinjs-core/compare/master...presentation/content-after-imodel-changes). @Rock2000, can you have a look at the test and your set up and see if there're any differences?

A few notes:
- `updatesPollInterval` is required when calling `Presentation.initialize` on the backend for changes to be tracked.
- You'll notice some hacks in my test related to IPC and Txns - those should not be necessary in a real set up.

**Comment by Rock2000** [comment] 2024-01-02 16:53
The { caching: { content: { size: 0 } } } options seems to 'fix' it, if that helps any. Let me try to look at the test

**Comment by Rock2000** [comment] 2024-01-02 19:07
Setting updatesPollInterval:1 also seemed to fix it. Is that the correct fix? Does it make sense that things seemed to work previously without this flag? Also I'm not sure how to pick a good value. What is occurring during this interval? Is it polling the backend from the frontend?

**Comment by grigasp** [comment] 2024-01-03 06:04
> Setting updatesPollInterval:1 also seemed to fix it. Is that the correct fix?

Yes, setting `updatesPollInterval` is the correct fix. I figure neither name nor the docs of this attribute are perfect - I filed [an issue](https://github.com/iTwin/itwinjs-core/issues/6338) for improving that.

> Does it make sense that things seemed to work previously without this flag?

Setting the attribute does two things (both on the backend):
1. Registers iModel data changes listener that clears affected entries from various caches and creates "update records" describing what changed. 
2. In our TS backend part, polls the "update records" from addon at the specified interval and streams them to the frontend for components to know what to update.

In `dev.25` there was a bug that caused us to always miss cached content entries, so you always got fresh content even without clearing the cache entries. With that bug fixed, performing the step 1 above became important.

Without this attribute, even in `dev.25`, I would assume the property grid didn't auto-reload when you changed a value, did it?

> Also I'm not sure how to pick a good value. What is occurring during this interval? Is it polling the backend from the frontend?

See above for what it's polling. Polling happens on the main backend's thread, so I would avoid setting this to something smaller than 5 ms. On the other hand, setting a large poll interval will make components "lag" to update, so it probably shouldn't be larger than 20 ms or similar.

**Comment by Rock2000** [comment] 2024-01-03 14:41
Yeah the property grid did refresh automatically in 25 and even earlier. We've had the property grid added for a couple months, and although we don't use it much yet it has seemed to work up until 37. 
But I'll add the polling value as that does fix it. Thanks

**Comment by grigasp** [comment] 2024-01-04 06:34
Closing this issue as it's now resolved and further improvements will be tracked by https://github.com/iTwin/itwinjs-core/issues/6338.

**Closed by grigasp** 2024-01-04 06:34 UTC
Labels: bug, property widget
